[core]
    debug = false
    data_dir = "../assets/"
    [core.data_files]
        dict = "ecdict.json"          # 词典数据
        etym = "etym.json"              # 词源数据
        lemma = "lemma.en.txt"          # 词干数据
        trans = "trans.json"            # 翻译数据

#WEB服务器设置
[webserver]
    addr = ":9009"                         #监听地址
    enable_ssl = false                     #是否使用https, 如果为true, 则必须配置cert和key的路径
    static_dir = "../webui/statics/"
    rpc_addr = "127.0.0.1:5431"           #RPC地址
    review_addr = ":80"                   #Review服务地址

# 登陆非对称加密
[login]
public_key = "configs/login/public_key.pem"     #login公钥
private_key = "configs/login/private_key.pem"   #login私钥

#证书设置
[webserver.certificates]
    cert = "certs/chaind.pem"            #证书路径
    key = "certs/domain.etym.key"        #Key路径

# Mysql server config
[database]
    host = "localhost"
    port = 3306
    dbname = "etym"
    username = "root"
    password = "root"
    args = "charset=utf8"
    buf_size = 10
    max_idle_conns = 20
    max_open_conns = 15
    show_sql = false
